name: Build and Zip Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Bump version
        run: pnpm run bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build extension
        run: pnpm run build

      - name: Extract version number
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Zip extension
        run: |
          mkdir -p output
          cd dist
          zip -r ../output/ocra-extension-${{ env.VERSION }}.zip .

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ocra-extension-${{ env.VERSION }}
          path: output/ocra-extension-${{ env.VERSION }}.zip

      - name: Push version bump commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "Bump version"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
