name: Build and Zip Chrome Extension

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This gives the workflow permission to push to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Bump version
        run: pnpm run bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build extension
        run: pnpm run build

      - name: Extract version number
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Zip extension
        run: |
            ls -la
            cd dist
            mkdir -p ../output
            ls -la ../output
            zip -r ../output/ocra-extension-${{ env.VERSION }}.zip .

      - name: Add all changes to git
        run: |
            git add -A
  
      - name: Commit changes
        run: |
            git commit -m "Bump version to ${{ env.VERSION }}"
        continue-on-error: true  # To handle cases where there might be no changes to commit
  
      - name: Push changes
        run: git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
            name: ocra-extension-${{ env.VERSION }}
            path: output/ocra-extension-${{ env.VERSION }}.zip
  